version: "3.9"

services:
  app:
    build: ./server
    container_name: steamtg-container
    restart: always
    ports:
      - "8989:8989"
    environment:
      - DATABASE_URL=postgres://postgres:Zxcvbnm123@db:5432/steamtg_db?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: steamtg-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zxcvbnm123
      POSTGRES_DB: steamtg_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
